services:
  autoparts.db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=autoparts
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./autoparts_dump.sql:/docker-entrypoint-initdb.d/autoparts_dump.sql
    networks:
      - autoparts-network
  autoparts.api:
    build: ./autoparts_api
    image: autoparts.api:latest
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=autoparts.db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=autoparts
      - MYSQL_PORT=3306
    depends_on:
      - autoparts.db
    networks:
      - autoparts-network  
  autoparts.client:
    build: 
      context: ./autoparts-client
      args:
        NEXT_PUBLIC_API_URL: http://autoparts.api:8000
    image: autoparts.client:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://autoparts.api:8000
    depends_on:
      - autoparts.api
    networks:
      - autoparts-network
networks:
  autoparts-network:
    driver: bridge