# Generated by Django 6.0.2 on 2026-02-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    def load_categories(apps, schema_editor):
        Category = apps.get_model('autoparts', 'Category')
        Category.objects.bulk_create([
            Category(name='Motor'),
            Category(name='Transmision'),
            Category(name='Frenos'),
            Category(name='Suspension'),
            Category(name='Electricos'),
        ])

    def load_brands(apps, schema_editor):
        Brand = apps.get_model('autoparts', 'Brand')
        Brand.objects.bulk_create([
            Brand(name='Toyota'),
            Brand(name='Ford'),
            Brand(name='Honda'),
            Brand(name='Chevrolet'),
            Brand(name='Nissan'),
        ])

    def load_providers(apps, schema_editor):
        Provider = apps.get_model('autoparts', 'Provider')
        Provider.objects.bulk_create([
            Provider(name='Proveedor A'),
            Provider(name='Proveedor B'),
            Provider(name='Proveedor C'),
            Provider(name='Proveedor D'),
            Provider(name='Proveedor E'),
        ])
    
    def load_autoparts(apps, schema_editor):
        AutoPart = apps.get_model('autoparts', 'AutoPart')
        Category = apps.get_model('autoparts', 'Category')
        Brand = apps.get_model('autoparts', 'Brand')
        Provider = apps.get_model('autoparts', 'Provider')

        auto_parts_data = [
            {
                'code': 'APA-001',
                'name': 'Filtro de Aceite',
                'description': 'Filtro de aceite para motores de gasolina.',
                'stock': 50,
                'min_stock': 10,
                'unit_price': 15.99,
                'category': Category.objects.get(name='Motor'),
                'brand': Brand.objects.get(name='Toyota'),
                'provider': Provider.objects.get(name='Proveedor A'),
                'storage_location': 'A-12-03'
            },
            {
                'code': 'APA-002',
                'name': 'Pastillas de Freno',
                'description': 'Juego de pastillas de freno para vehículos compactos.',
                'stock': 30,
                'min_stock': 5,
                'unit_price': 45.50,
                'category': Category.objects.get(name='Frenos'),
                'brand': Brand.objects.get(name='Ford'),
                'provider': Provider.objects.get(name='Proveedor B'),
                'storage_location': 'B-12-03'
            },
            {
                'code': 'APA-003',
                'name': 'Amortiguadores',
                'description': 'Amortiguadores para suspensión trasera.',
                'stock': 20,
                'min_stock': 5,
                'unit_price': 120.00,
                'category': Category.objects.get(name='Suspension'),
                'brand': Brand.objects.get(name='Honda'),
                'provider': Provider.objects.get(name='Proveedor C'),
                'storage_location': 'C-12-03'
            },
        ]

        auto_parts_instances = [AutoPart(**data) for data in auto_parts_data]
        AutoPart.objects.bulk_create(auto_parts_instances)

    dependencies = [
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_categories),
        migrations.RunPython(load_brands),
        migrations.RunPython(load_providers),
        #migrations.RunPython(load_autoparts),
    ]


    